{% set version = "1.12" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-paramhelpers
  version: {{ version|replace("-", "_") }}

source:
  fn: ParamHelpers_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ParamHelpers_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ParamHelpers/ParamHelpers_{{ version }}.tar.gz
  sha256: b54db9e6608ba530345c380c757a60cb2b78ab08992a890b1a41914ce7abcc14

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bbmisc >=1.10
    - r-backports
    - r-checkmate >=1.8.2
    - r-fastmatch
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bbmisc >=1.10
    - r-backports
    - r-checkmate >=1.8.2
    - r-fastmatch

test:
  commands:
    - $R -e "library('ParamHelpers')"           # [not win]
    - "\"%R%\" -e \"library('ParamHelpers')\""  # [win]

about:
  home: https://github.com/berndbischl/ParamHelpers
  license: BSD_2_clause
  summary: Functions for parameter descriptions and operations in black-box optimization, tuning
    and machine learning. Parameters can be described (type, constraints, defaults,
    etc.), combined to parameter sets and can in general be programmed on. A useful
    OptPath object (archive) to log function evaluations is also provided.
  license_family: BSD

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
