# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "J8QYSxDv6bT/tO1gK1bDETsC2r4fax3dsSdAR8ylLyiE0tFvcgygywRkOVzkwfZ9gEo9Mi+UtDI1R47b0BK3RRaSgvfHXvXwT4joRqVKHoaIg6Id1ex44BSL3BD/NpTlYQvHmI6faZaxyZlvzkuPxF2MCwfY/gu6fXDDhpEqB9ptLVN77JEONb/3WYJ4dr9gcq4poJ7UPA1ATosObkthhv6benEf/a4dv84FyO0si3QG916+vL+suesvYUkA3PN/zVRZ/N3sD4Dl56vBa8gTOpNMZ23wrDkIRbHLFpm+VwEC65LKDaPpCGmOBJWxY9ZviPPcrqaNM8cqwCQYtw/GxcwMEL2b+09nw/E36mR50/afXBGjU54H6GpdhOKKZNQN5d1d2R2E5SIJ6tsJg+KOuCC1fjgsJEuPRl6zsxGtj1nYPj27xm1zpxHyThH4GZQFG8dO3W2HKM5KVhGqh9DWF7YQhKdhjQ/IuPIxN2t4ZgB2fLlDWFboqDp5q8BuovlIGC/td8pyJ1QIeELvyxlr6QzZHl6bKcVvKknxZU9d9rTYWqVzWmi6ruFKm7orpqHWOoQzbYHEbVTcvScZg0SDJNMxLoND1CLcgtOLrg3v8OmdvIVnVajfQ4FEYW+h3aqeuh5NxF3wTkSkgY2aRV/NA3+RgjqzqE/h2ZMPMyeu5qE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml