travis:
  secure:
    BINSTAR_TOKEN: gnuH2gL08tVjk6Qco6vYpwCRp7ReL20IEgh3L868FzCgDzgeMLVXcXo2bBbcV5Y3tUddgML9sO2+1IlKtgsj47ZybVTyRWWFJZuHyzsWw6nhu8gOiSaCkyKlByRM8MgxPXZhXyZWKSV2/rd5I9sojqzDmv+GQNS/SWA/TC2JyVEyQ61xTuGi0yqqV87CK5WJtfPoJYTjH601Uh8LC15sFx4UCqZUUKwYz4mbshShJHP9qWbyUKB3GccMsdxw11wpWcKOaoTOlG0C67jWAOUnlLBRU+sZ+rPrIfH5P4L5LH8J4U2DRFxmrG4mK/z2zKrXigQpG4bY8QEvR7mbkJjpKjFEQC+v/PY06jDxabob+jtct9UAFrM5NyccDQOqLcelTumk1HEOi0eQl7/+Xs9i5qRZaywoHlFrWL67nkSQhYtX2hnd0f6+hhAdZdlo48wGESbkDcNbRi5x+PsViQZL86s8o9YLfhm7b3KSu9DKDREAvw/cXJMJaRTXTVZAzlTOwuLSyNjShwNg/vB1DDbOACLRkuIG9VqFE6oCAn9Teef3AYK33UYn2e0FIPuPO9EWXyR6gmWG3xKJNeBeXcYGELnEb3APQPxpEeSDpXVAO/39ITuOfbVudIgmKHrjZJG+yMJ3RDITqHh5dXz3xgFQh36WXG85A/xaZ9g1c5A8ogA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
